### ISSUE TITLE
How to check the database info with trivy.db and trivy-light.db?

### ISSUE THREAD

**Issue by yehching0109** [aquasecurity/trivy-db#112]
Hi all,

As the mention above, how should i open the two files downloaded from the site?
I want to see the difference between them.
Any suggestions?
The main reason is that when i use trivy scan the same image, but with --light will not encountered vulnerability report and without --light will.
But the "--light" was only different from not showing the description and the CVE reference ?

Thanks,

**Comment by knqyf263** [comment]
I'm using https://github.com/br0xen/boltbrowser

**Comment by yehching0109** [comment]
Hi @knqyf263 ,
Thanks for the reply, but i couldn't use the boltbrowser.
I had already go get install the boltbrowser, but when im using "boltbrowser myfile", command not found happened.

**Comment by knqyf263** [comment]
You need to add `$GOPATH` to `$PATH` like `export PATH=$PATH:$GOPATH/bin`.

**Comment by yehching0109** [comment]
Thanks for the reply.
I used hxd to watch the databse instead.
Problem solved.
