### ISSUE TITLE
Debian 11 Support needed.

### ISSUE THREAD

**Issue by ziozzang** [aquasecurity/trivy-db#138]
Debian 11 was just released. :)

Need update vulsrc with mapping code.

**Comment by knqyf263** [comment]
Thanks. We have to update this mapping.
https://github.com/aquasecurity/trivy-db/blob/da8e09204404011a63e5eef8700b5ec3138484fa/pkg/vulnsrc/debian/debian.go#L27-L36

**Comment by thepwagner** [comment]
I've done this in https://github.com/aquasecurity/trivy-db/pull/136 , just needs review 🚀
