### ISSUE TITLE
trivy-db latest Version has an old schema

### ISSUE THREAD

**Issue by jaskaransarkaria** [aquasecurity/trivy-db#186]
Currently downloading the latest trivy-offline-db and using these assets in an air gapped environment raises the following error:

```sh
2022-02-01T11:06:40.539Z        ERROR   The local DB has an old schema version which is not supported by the current version of Trivy CLI. It
needs to be updated.
2022-02-01T11:06:40.539Z        FATAL   DB error: database error: validate error: --skip-update cannot be specified with the old DB schema
```

Replicate with these cmds:

```
wget https://github.com/aquasecurity/trivy-db/releases/latest/download/trivy-offline.db.tgz
mkdir -p trivy/db
cd trivy/db
tar xvf trivy-offline.db.tgz

# verify the matadata
cat metadata.json
# File: metadata.json 
# {"Version":1,"Type":1,"NextUpdate":"2022-02-01T12:39:57.229393312Z","UpdatedAt":"2022-02-01T06:39:57.229393912Z","DownloadedAt":"0001-01-01T00:00:00Z"}

# run trivy
cd ..
TRIVY_CACHE_DIR=$(pwd) trivy image --skip-update alpine:latest

# see above error
```
As a dirty hack you can supress the error with:

`sed -i 's/\"Version\"\:1/"Version":2/g' db/metadata.json`

and then rerun the above trivy command.

Although this obviously isn't ideal.

Can we get a fix for this ASAP as removing the `--skip-update` from from our air gapped enviroment isn't possible.

Thanks

**Comment by knqyf263** [comment]
See here
https://aquasecurity.github.io/trivy/v0.23.0/advanced/air-gap/

**Comment by aasyria** [comment]
same Error here, i tried also some old version of the DB and did not work. I think it is trivy Problem and not trivy DB, what do you think ?

**Comment by afdesk** [comment]
> same Error here, i tried also some old version of the DB and did not work. I think it is trivy Problem and not trivy DB, what do you think ?

@aasyria I could download `trivy.db` version 2. 
but I used `oras` for it:
```sh
$ oras pull ghcr.io/aquasecurity/trivy-db:2 -a
```

**Comment by afdesk** [comment]
also you can download the new db to cache via `trivy` option:
```
$ trivy image --download-db-only
```

**Comment by aasyria** [comment]
> also you can download the new db to cache via `trivy` option:
> 
> ```
> $ trivy image --download-db-only
> ```

this but not an air gapped environment

**Comment by jaskaransarkaria** [comment]
Thanks for the quick reply, I haven't tried the oras solution yet. I will get back to you, I will attempt it tomorrow morning (uk time) and post back with my findings

**Comment by aasyria** [comment]
sed -i 's/\"Version\"\:1/"Version":2/g' db/metadata.json

it tried to change the Version and it worked but the trivy does not scan anything

**Comment by aasyria** [comment]
https://github.com/aquasecurity/trivy/issues/1623 

this solved the problem 
I just reused older version of Trivy until solving the Problem 
what I think the problem is that the CLI tool does not read the new schema correctly and that is why I did not find any new vulnerability when you scan 
I suggest adding a new flag to chose which schema you want to use.
When you download the DB from the Releases the Schema Version is "1" and when the CLI pulled the Schema Version is "2"

**Comment by afdesk** [comment]
> sed -i 's/"Version":1/"Version":2/g' db/metadata.json
> 
> it tried to change the Version and it worked but the trivy does not scan anything

such change won't work correctly, because the db struct was changed.

**Comment by afdesk** [comment]
@aasyria where are you getting the database from?

**Comment by kotaner** [comment]
Same here, we upgraded cli to latest and started having this issue. 
trivy-offline.db.tgz has this inside metadata.json : 
{"Version":1,"Type":1,"NextUpdate":"2022-02-03T06:49:29.03387375Z","UpdatedAt":"2022-02-03T00:49:29.03387415Z","DownloadedAt":"0001-01-01T00:00:00Z"}

db downloaded with trivy image --download-db-only has this :
{"Version":2,"NextUpdate":"2022-02-03T06:11:32.374652962Z","UpdatedAt":"2022-02-03T00:11:32.374653162Z","DownloadedAt":"2022-02-03T03:42:12.668613247Z"}

**Comment by afdesk** [comment]
@kotaner thanks for your interest in `trivy`!
could you tell me where and how you get `trivy-offline.db.tgz`?
do you use `oras`?
thanks

**Comment by aasyria** [comment]
> @kotaner thanks for your interest in `trivy`! could you tell me where and how you get `trivy-offline.db.tgz`? do you use `oras`? thanks

I got it from the Releases

**Comment by aasyria** [comment]
[#1667](https://github.com/aquasecurity/trivy/issues/1667)
after reading the release of the new version [0.23.0](https://github.com/aquasecurity/trivy/discussions/1652) of trivy i think  there is no issue . 
the [documentation](https://github.com/aquasecurity/trivy/blob/main/docs/advanced/air-gap.md) is now updated and you need to download the database using [oras](https://oras.land/cli/)

**Comment by 06kellyjac** [comment]
for those of you that use crane from go-containerregistry (also needs jq)

```
getDB() {
	OLDDIR="$PWD"
	TMPDIR="$(mktemp -d)"
	cd "$TMPDIR" || exit 1
	crane pull "$1" file.tar.gz
	FILENAME="$(crane manifest "$1" | jq -r .layers[0].digest | cut -d':' -f2).tar.gz"
	tar xf file.tar.gz "$FILENAME"
	cd "$OLDDIR" || exit 1
	mv "$TMPDIR/$FILENAME" "db.tar.gz"
}

# then run:

getDB ghcr.io/aquasecurity/trivy-db:2
```

manual steps without jq would be:
* `crane pull ghcr.io/aquasecurity/trivy-db:2 file.tar.gz`
* `tar xvf file.tar.gz`
* rename the only `xyz.tar.gz` file that comes out to `db.tar.gz`
  * (will be `ea16e13078e8e8186d949ab68eec78ee67fbfd537ce61725e55bf66589a7da18.tar.gz` or similar)

**Comment by kotaner** [comment]
> @kotaner thanks for your interest in `trivy`! could you tell me where and how you get `trivy-offline.db.tgz`? do you use `oras`? thanks

I got it from github releases, now seeing you guys have updated documentation. it is confusing to switch to new db format and keep releases with older version of db still laying around. All good now.

**Comment by jaskaransarkaria** [comment]
> See here https://aquasecurity.github.io/trivy/v0.23.0/advanced/air-gap/

This solution worked for us, I will close the issue. It looks as though some of the comments still are having problems implementing a solution for their particular setup, I suggest you open a different issue with you're particular scenarios.

Thanks.
