### ISSUE TITLE
unable to pull image

### ISSUE THREAD

**Issue by pschulten** [aquasecurity/trivy-db#202]
tried on different machines
I get 
```
$ docker pull ghcr.io/aquasecurity/trivy-db:2
2: Pulling from aquasecurity/trivy-db
2201a50a2e17: Pulling fs layer
unexpected end of JSON input
```

**Comment by knqyf263** [comment]
Try oras, not docker.
https://aquasecurity.github.io/trivy/v0.25.3/docs/advanced/air-gap/

**Comment by pschulten** [comment]
yes this works. Sorry, didn't re-read the air-gap docs :(
Is it possible to customize the `Install from the command line:` tip at https://github.com/aquasecurity/trivy-db/pkgs/container/trivy-db to reflect that?

**Comment by knqyf263** [comment]
It is automatically generated by GitHub. I have no idea how to modify it...
