### ISSUE TITLE
The local DB has an old schema version which is not supported by the current version of Trivy CLI. DB needs to be updated.

### ISSUE THREAD

**Issue by ronaldshaooo** [aquasecurity/trivy-db#218]
I'm using harbor v2.5.1 and download latest trivy-db. I have to use offline version both of them and it show me "The local DB has an old schema version which is not supported by the current version of Trivy CLI. DB needs to be updated.", "--skip-update cannot be specified with the old DB schema."

Offline db worked until harbor v2.4.1, any suggestion?

Thanks.

**Comment by flavienbwk** [comment]
@knqyf263 it doesn't. I've tried downloading the [last offline DB release](https://github.com/aquasecurity/trivy-db/releases/download/v1-2022062818/trivy-offline.db.tgz) from this repo, putting it in `$HOME/.cache/trivy/db` without success.

> ERROR : The local DB has an old schema version which is not supported by the current version of Trivy 
CLI. DB needs to be updated

Version I use : 0.29.2

Thank you for your help.

**Comment by knqyf263** [comment]
Again, please read the doc. The offline database you mentioned is no longer used. You might read the old doc. Please take a read at the latest one.
