### ISSUE TITLE
replace `utils/strings/InSlice` to `slices.Contains`

### ISSUE THREAD

**Issue by afdesk** [aquasecurity/trivy-db#245]
Now we don't need this deprecated function `InSlice`:

https://github.com/aquasecurity/trivy-db/blob/main/pkg/utils/strings/strings.go#L28-L35

**Comment by souravsk** [comment]
@afdesk i just have to delete the inslice function.

**Comment by afdesk** [comment]
@souravsk it seems Go version should be bumped up 1.18 for using `slices.Contains`. need to test it

**Comment by souravsk** [comment]
Okay so are you going to update the go version

**Comment by rustiever** [comment]
@afdesk can i take up this ??
