### ISSUE TITLE
DB archive file download from Github Release not work because version in metadata.json mismatch with version of db

### ISSUE THREAD

**Issue by Riohyc** [aquasecurity/trivy-db#249]
```
trivy version
Version: 0.30.4
```
### Download latest db from github release and unarchive it to cache dir:
```
mkdir -p /tmp/trivy/.cache/db
wget https://github.com/aquasecurity/trivy-db/releases/download/v1-2022090506/trivy-offline.db.tgz -O db.tar.gz
tar xzf ./db.tar.gz -C /tmp/trivy/.cache/db
```
```
cat /tmp/trivy/.cache/db/metadata.json
{"Version":1,"Type":1,"NextUpdate":"2022-09-05T12:50:05.096459442Z","UpdatedAt":"2022-09-05T06:50:05.096459842Z","DownloadedAt":"0001-01-01T00:00:00Z"}
```

Here is metadata.json in db archive file pull from GHCR
```
cat metadata.json
{"Version":2,"NextUpdate":"2022-09-03T12:07:00.39779422Z","UpdatedAt":"2022-09-03T06:07:00.39779462Z","DownloadedAt":"0001-01-01T00:00:00Z"}
```
### Try run scan with latest trivy:
```
trivy --cache-dir /tmp/trivy/.cache image --skip-update --format json SOME_IMAGE
2022-09-05T12:51:41.402Z        ERROR   The local DB has an old schema version which is not supported by the current version of Trivy CLI. DB needs to be updated.
2022-09-05T12:51:41.402Z        FATAL   init error: DB error: database error: validate error: --skip-update cannot be specified with the old DB schema. Local DB: 1, Expected: 2
```

Here is difference between *Github Release* and *Trivy DB* action:

Github Release
https://github.com/aquasecurity/trivy-db/runs/8183176380?check_suite_focus=true#step:9:1
Trivy DB
https://github.com/aquasecurity/trivy-db/runs/8188045536?check_suite_focus=true#step:9:1

Looks like *Github Release* missing environment?

**Comment by afdesk** [comment]
@Riohyc no, you download the old database. you need to use `oras` or `trivy` for it.

read more: https://aquasecurity.github.io/trivy/v0.31.3/docs/advanced/air-gap/

**Comment by Riohyc** [comment]
> @Riohyc no, you download the old database. you need to use `oras` or `trivy` for it.
> 
> read more: https://aquasecurity.github.io/trivy/v0.31.3/docs/advanced/air-gap/

So, the only way to download correct version of db is pulling from GCHR by `oras` or `trivy`? Even the Github Release is outdated?

**Comment by afdesk** [comment]
> So, the only way to download correct version of db is pulling from GCHR by `oras` or `trivy`? Even the Github Release is outdated?

yes,  i think that  the Github Release is for backward compatibility now
