### ISSUE TITLE
metadata.json 's Version need update to 2 when use newest trivy

### ISSUE THREAD

**Issue by guos** [aquasecurity/trivy-db#250]
the offline db 's metadata.json not work when use new trivy like version 0.31.2/3, it will say db version not correct and when change the Version from 1 to 2 works

{"Version":1,"Type":1,"NextUpdate":"2022-09-06T06:52:19.891405769Z","UpdatedAt":"2022-09-06T00:52:19.891406469Z","DownloadedAt":"0001-01-01T00:00:00Z"}

change to follow works

{"Version":**2**,"Type":1,"NextUpdate":"2022-09-06T06:52:19.891405769Z","UpdatedAt":"2022-09-06T00:52:19.891406469Z","DownloadedAt":"0001-01-01T00:00:00Z"}

**Comment by knqyf263** [comment]
Duplicated
https://github.com/aquasecurity/trivy-db/issues/249
