### ISSUE TITLE
Missing Distribution Versions in Trivy DB

### ISSUE THREAD

**Issue by DorHayun** [aquasecurity/trivy-db#253]
Hi team,
It seems like you have added the support for Amazon linux 2022, Oracle linux 9 and the Ubuntu 22.04 but i can't see it in the latest
DB downloaded from the
https://github.com/aquasecurity/trivy-db/releases/latest/download/trivy.db.gz

Where can i get the latest db to download?
thanks

**Comment by afdesk** [comment]
@DorHayun your link refers to the version 1, now Trivy uses trivy.db version 2.

you can download it via `oras`. Read more here: [Download the vulnerability database](https://aquasecurity.github.io/trivy/v0.32/docs/advanced/air-gap/)

**Comment by afdesk** [comment]
now this information was added to README: [Download the vulnerability database](https://github.com/aquasecurity/trivy-db#download-the-vulnerability-database)
