### ISSUE TITLE
Trivy offline db v2

### ISSUE THREAD

**Issue by ExitoLab** [aquasecurity/trivy-db#255]
We need to be able to download the offline db v2. But currently we only have v1 

Pls see links https://github.com/aquasecurity/trivy-db/releases 

The current version of trivy v.33.0 is only compatible with v2 offline database. 

Pls how do i get v2 offline db for trivy

**Comment by afdesk** [comment]
you need to use  `oras` for it:
```sh
$ oras pull ghcr.io/aquasecurity/trivy-db:2
```

please, read the documentation: https://aquasecurity.github.io/trivy/v0.32/docs/advanced/air-gap/
