### ISSUE TITLE
Add custom put support for AlmaLinux

### ISSUE THREAD

**Issue by srinivasKandukuri** [aquasecurity/trivy-db#269]
Right now we don't have an option to extend alma to build a custom database on top of Trivy DB. Add CustomPut and CustomDB 
like ubuntu ref# https://github.com/aquasecurity/trivy-db/blob/main/pkg/vulnsrc/ubuntu/ubuntu.go#L65

**Comment by knqyf263** [comment]
https://github.com/aquasecurity/trivy-db/pull/268
