### ISSUE TITLE
Error getting vulnerability DB

### ISSUE THREAD

**Issue by eran-medan** [aquasecurity/trivy-db#294]
I've been getting 2 errors that might be related. 

1. When running trivy (any command) `FATAL	init error: DB error: failed to download vulnerability DB: OCI artifact error: OCI artifact error: OCI repository error: Get "https://ghcr.io/v2/": dial tcp: lookup ghcr.io: i/o timeout` 
2. When trying to pull the db image: `unsupported media type application/vnd.aquasec.trivy.config.v1+json`

I didn't see any issue with github packages https://www.githubstatus.com/

**Comment by knqyf263** [comment]
>When trying to pull the db image: unsupported media type application/vnd.aquasec.trivy.config.v1+json

It is not a container image. I guess you used docker CLI or something like that.

Did you try `$ oras pull ghcr.io/aquasecurity/trivy-db:2`?

**Comment by zangcc** [comment]
When I use the command $ oras pull ghcr.io/aquasecurity/trivy-db:2 to download, it keeps displaying Downloading ab9f83222a54 db.tar.gz, and then the whole terminal is silent. This db.tar.gz cannot be downloaded. How to solve it?

**Comment by knqyf263** [comment]
It works in my environment.

```
$ oras pull ghcr.io/aquasecurity/trivy-db:2
Downloading ab9f83222a54 db.tar.gz
Downloaded  ab9f83222a54 db.tar.gz
Pulled [registry] ghcr.io/aquasecurity/trivy-db:2
Digest: sha256:6e8ec44dd954d39f275bd607a677231843d54210b03f86d353652cc8c8f1b132
```

Oras doesn't show any progress. I guess your network is slow, and it just takes a long time to download it.
