### ISSUE TITLE
is there a Mirror address?

### ISSUE THREAD

**Issue by wang-xiaowu** [aquasecurity/trivy-db#308]
i am using trivy 0.4.1, and it needs nearly update the db everyday, but too slow from 'ghcr.io/aquasecurity/trivy-db'
is there a Mirror address?

**Comment by wang-xiaowu** [comment]
done
i found the mirror address

**Comment by Sjord** [comment]
public.ecr.aws/aquasecurity/trivy-db:2

```
$ trivy image --db-repository public.ecr.aws/aquasecurity/trivy-db:2 YOUR_IMAGE
```
