### ISSUE TITLE
Push trivy-db container image to a registry

### ISSUE THREAD

**Issue by mrueg** [aquasecurity/trivy-db#31]
I'd like to request
* Automated builds of trivy and trivy-light db with Github 
* Automated pushes of the db to dockerhub or another registry

This would allow users to start including the container image in trivy.

**Comment by knqyf263** [comment]
@mrueg Do you have any idea about how to extract the db file from the iamge?

Do we need to create an image once?
```
id=$(docker create image-name)
docker cp $id:path - > local-tar-file
docker rm -v $id
```

**Comment by mrueg** [comment]
A few options:

1. I think the easiest way for users would be to re-use the logic that gets applied to scan a container image and extract the tarball from the trivydb image.
something along the lines of:
``` trivy --db-image trivy-db:latest alpine:3.9```

trivy then would 
* fetch trivy-db:latest from a registry
* open the container image
* extract the db from there

2. If you run trivy inside a docker image, you can use a bind mount (this is untested regarding paths):
```docker run --rm -v --mount source=trivy-db:latest,target=/root/.cache/ aquasec/trivy python:3.9-alpine ```


3. If you run trivy inside kubernetes (e.g. as a job) you can run a sidecar which trivy mounts volumes from similar to 2.

**Comment by knqyf263** [comment]
Thanks! As for the first option, it requires some implementation in trivy. It seems difficult to do it shortly. The second and third options look great. It might not work at the moment due to this [commit](https://github.com/aquasecurity/trivy/pull/464). I'll check it.

**Comment by neha-viswanathan** [comment]
Hello @knqyf263 @mrueg any updates on this?

**Comment by knqyf263** [comment]
DockerHub added late limits, but do you still want to put trivy-db to DockerHub?
https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/
