### ISSUE TITLE
outdated trivy db

### ISSUE THREAD

**Issue by smtan-gl** [aquasecurity/trivy-db#333]
Hi, it appears that the most recent version of `trivy-db` is `2023-07-20T12:11:37.696263932Z`, which is likely caused by the [DB build failures](https://github.com/aquasecurity/trivy-db/actions). Any idea how long it might take to resolve this and if there's a workaround?

Thank you! 😄

**Comment by knqyf263** [comment]
Worked around
https://github.com/aquasecurity/trivy-db/pull/334
