### ISSUE TITLE
GHSA source for rust ignored

### ISSUE THREAD

**Issue by hamiltop** [aquasecurity/trivy-db#353]
OSV uses `vulnerability.Cargo` but GHSA uses `vulnerability.Rust`  (or maybe the other way around?)

Adding:
```
		if ecosystem == vulnerability.Rust {
			dataSources[vulnerability.Cargo] = src
		}
```
to `func (GHSA) Update(root string) error` makes it build the db properly and then using the db with `trivy` correctly finds vulnerabilities against Cargo.

**Comment by knqyf263** [comment]
https://github.com/aquasecurity/trivy-db/pull/355
