### ISSUE TITLE
How nvr-to-cpe.json is generated

### ISSUE THREAD

**Issue by wopashugeixianshi** [aquasecurity/trivy-db#354]
As stated in the title, I can't  find the process of generating the file

**Comment by knqyf263** [comment]
The script is maintained in a private repository.

**Comment by wopashugeixianshi** [comment]
> 

So, is this script provided externally

**Comment by wopashugeixianshi** [comment]
> The script is maintained in a private repository.

So, is this script provided externally？

**Comment by knqyf263** [comment]
It is not provided, just for our internal use.
