### ISSUE TITLE
Publishing Trivy DB is failing

### ISSUE THREAD

**Issue by fawind** [aquasecurity/trivy-db#383]
Hey, just wanted to raise this in case it's not known yet:

The scheduled Trivy DB Github Action has started failing persistently since Feb 13 ([GH Actions](https://github.com/aquasecurity/trivy-db/actions)).

It's erroring out with ([example run](https://github.com/aquasecurity/trivy-db/actions/runs/7911759389)):

```
System.IO.IOException: No space left on device : '/home/runner/runners/2.313.0/_diag/Worker_20240213-180155-utc.log'
```

This is blocking new releases of the Trivy DB from getting published.

According to [Github docs](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories) Github-hosted runners only come with 14GB disk space guaranteed. Not sure how much disk space we can easily safe while building the Trivy DB, but maybe reducing log volume could help as a temporary fix?

**Comment by knqyf263** [comment]
Thanks for the heads-up. @DmitriyLewen Can you please take a look? I'm wondering if vuln-list consumes such disk spaces.

**Comment by knqyf263** [comment]
It works now.

**Comment by fawind** [comment]
Amazing! Thanks for the quick fix and also all the great work you're doing for Trivy 🎉

**Comment by knqyf263** [comment]
@fawind Thanks for your help!
