### ISSUE TITLE
Amazon Linux 2023 flagged as EOL

### ISSUE THREAD

**Issue by Xeroxxx** [aquasecurity/trivy-db#390]
Amazonlinux is flagged as EOL for 2 days now.

Reason seems to be a change of the version schema in /etc/*elease files. Changing from Amazon Linux 2023 to Amazon Linux release 2023.3.20240304 (dynamic).

Reproduce:
Pull Image Amazon Linux 2023 from ECR (latest)
Pull Image Amazon Linux 2023 from DockerHub (older)

Error Message:
ERROR	Detected EOL OS: amazon 2023.3.20240304 (Amazon Linux)

Code to blame:
https://github.com/aquasecurity/trivy-db/blob/db9bf07792afba73dceb20b99723c8af007da1f8/pkg/vulnsrc/amazon/amazon.go#L98

Proposal: 
Check first digits till dividing dot match targetVersion (for 2023 and newer) or check "VERSION" (present in 2 and 2023)

NEW vs OLD:
![image](https://github.com/aquasecurity/trivy-db/assets/1109954/2c332b65-2b88-4a7b-a932-1e46b6793d26)

Thank you

**Comment by knqyf263** [comment]
Thanks for the report. Yes, it is probably the cause. @DmitriyLewen Can you please take a look?

**Comment by DevTeamDbVertrieb** [comment]
Thank you for this extensive analysis. It explains everything for us. We currently have the same falsepostive message for all our services.

I think that helps a lot for a quick fix!
