### ISSUE TITLE
feat: support openSUSE Tumbleweed

### ISSUE THREAD

**Issue by msmeissn** [aquasecurity/trivy-db#410]
We now generate CVRF data for openSUSE Tumbleweed.

openSUSE Tumbleweed is versionless, as it is a rolling release.

The CVRF for it will also appear in the openSUSE-* CVRF space.

example CVRF:
https://ftp.suse.com/pub/projects/security/cvrf/cvrf-opensuse-su-2024%3A10400.xml

**Comment by knqyf263** [comment]
Thanks for updating! Is there anybody who can contribute from SUSE?
