### ISSUE TITLE
Scanning failure for non-amd64 Red Hat images created before June 2020

### ISSUE THREAD

**Issue by knqyf263** [aquasecurity/trivy-db#435]
## Description:
We've identified an issue in our scanning process for Red Hat container images.

### Problem
Scanning fails for Red Hat container images that meet both of these criteria:

- Created before June 2020
- Architecture other than amd64

### Root cause:

These older images lack `/root/buildinfo/content_manifests`, requiring NVR-to-CPE conversion.
Our current [NVR-to-CPE mapping](https://github.com/aquasecurity/vuln-list-redhat/blob/main/cpe/nvr-to-cpe.json) only includes amd64 architectures.

### Impact
Incomplete vulnerability scanning for affected images

**Comment by atgreen** [comment]
I'm getting this same error, pointing me at this Issue, despite the fact that the image DOES contain `/root/buildinfo/content_manifests`

```green@fedora:~/ctest$ trivy image registry.redhat.io/ocp-tools-4/jenkins-rhel8:v4.14.0-1725667424
2024-09-21T07:45:26-04:00	INFO	[vuln] Vulnerability scanning is enabled
2024-09-21T07:45:26-04:00	INFO	[secret] Secret scanning is enabled
2024-09-21T07:45:26-04:00	INFO	[secret] If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2024-09-21T07:45:26-04:00	INFO	[secret] Please see also https://aquasecurity.github.io/trivy/v0.55/docs/scanner/secret#recommendation for faster secret detection
2024-09-21T07:45:32-04:00	INFO	Detected OS	family="redhat" version="8.10"
2024-09-21T07:45:32-04:00	INFO	[redhat] Detecting RHEL/CentOS vulnerabilities...	os_version="8" pkg_num=375
2024-09-21T07:45:32-04:00	FATAL	Fatal error	image scan error: scan error: scan failed: scan failed: failed to detect vulnerabilities: unable to scan OS packages: failed vulnerability detection of OS packages: failed detection: redhat vulnerability detection error: failed to get Red Hat advisories: unable to find CPE indices. See https://github.com/aquasecurity/trivy-db/issues/435 for details
```

**Comment by knqyf263** [comment]
@DmitriyLewen Can you please take a look?

**Comment by DmitriyLewen** [comment]
Hello @atgreen 
It looks like the `content_manifests` file contains unknown repositories.

Unfortunately, I don't have access to this image.

Can you send me the `/root/buildinfo/content_manifests/*.json` file from this image?

**Comment by atgreen** [comment]
[out.txt](https://github.com/user-attachments/files/17095447/out.txt)

**Comment by DmitriyLewen** [comment]
looks like few files contains wrong `content_sets`:
```
====== /root/buildinfo/content_manifests/openshift-base-rhel8-container-v4.14.0-202408260910.p0.gf020942.assembly.stream.el8.json ======
{
    ...
    "content_sets": [
        "rhel-8-for-x86_64-appstream-rpms__8",
        "rhel-8-for-x86_64-baseos-rpms__8"
    ]
}====== /root/buildinfo/content_manifests/openshift-enterprise-base-container-v4.14.0-202408260910.p0.g03e5f40.assembly.stream.el8.json ======
{
    ...
    "content_sets": [
        "rhel-8-for-x86_64-appstream-rpms__8",
        "rhel-8-for-x86_64-baseos-rpms__8"
    ]
}====== /root/buildinfo/content_manifests/openshift-enterprise-cli-container-v4.14.0-202408260910.p0.g44b3ac2.assembly.stream.el8.json ======
{
    ...
    "content_sets": [
        "rhel-8-for-x86_64-appstream-rpms__8",
        "rhel-8-for-x86_64-baseos-rpms__8"
    ]
}====== /root/buildinfo/content_manifests/openshift-jenkins-2-container-v4.14.0-1725667424.json ====== 
{
    ...
    "content_sets": [
        "rhel-8-for-x86_64-baseos-rpms",
        "rhel-8-for-x86_64-appstream-rpms"
    ]
}====== /root/buildinfo/content_manifests/ubi8-container-8.10-901.1717584420.json ====== 
{
    ...
    "content_sets": [
        "rhel-8-for-x86_64-baseos-rpms",
        "rhel-8-for-x86_64-appstream-rpms"
    ],
    "image_contents": []
}

```
`rhel-8-for-x86_64-baseos-rpms` and `rhel-8-for-x86_64-appstream-rpms` are correct (see output of `Pyxis`).
`rhel-8-for-x86_64-appstream-rpms__8` and `rhel-8-for-x86_64-baseos-rpms__8` are wrong.

@knqyf263 you have more experience in this matter.
I have 2 question:
- IIUC `/root/buildinfo/content_manifests` should contain one manifest file. Is it correct that this directory contains more than 1 file?
- if yes - should we merge `content_sets` from these files?
   https://github.com/aquasecurity/trivy/blob/37d549e5b86a1c5dce6710fbfd2310aec9abe949/pkg/fanal/analyzer/analyzer.go#L294-L296

**Comment by knqyf263** [comment]
>IIUC /root/buildinfo/content_manifests should contain one manifest file. Is it correct that this directory contains more than 1 file?

My understanding is that there should only be one file per layer. However, the image as a whole may contain multiple files. Therefore, it is necessary to look up the appropriate buildinfo for each package.
https://github.com/aquasecurity/trivy/blob/37d549e5b86a1c5dce6710fbfd2310aec9abe949/pkg/fanal/applier/docker.go#L53-L76

**Comment by sayan-biswas** [comment]
This is the content set we have used in our config.
```
aarch64:
- rhel-8-for-aarch64-baseos-rpms
- rhel-8-for-aarch64-appstream-rpms
ppc64le:
- rhel-8-for-ppc64le-baseos-rpms
- rhel-8-for-ppc64le-appstream-rpms
s390x:
- rhel-8-for-s390x-baseos-rpms
- rhel-8-for-s390x-appstream-rpms
x86_64:
- rhel-8-for-x86_64-baseos-rpms
- rhel-8-for-x86_64-appstream-rpms
```

**Comment by knqyf263** [comment]
@sayan-biswas Thanks for sharing. We see some content sets, like `rhel-8-for-x86_64-appstream-rpms__8`. Is it legitimate or a mistake?

```
$ docker run --rm -it --entrypoint cat registry.redhat.io/ocp-tools-4/jenkins-agent-base-rhel8@sha256:b142a2461dcf8bc50cc6311808867c38a3de45c82145df648d34d37a75496d0f -- /root/buildinfo/content_manifests/openshift-enterprise-base-container-v4.15.0-202408260908.p0.g27f1695.assembly.stream.el8.json | jq .cont
ent_sets
[
  "rhel-8-for-aarch64-appstream-rpms__8",
  "rhel-8-for-aarch64-baseos-rpms__8"
]
```

**Comment by DmitriyLewen** [comment]
> This is the content set we have used in our config.

These content sets are contained in 4 files, right?
If yes - do you add these files in one layer?

> My understanding is that there should only be one file per layer. However, the image as a whole may contain multiple files. Therefore, it is necessary to look up the appropriate buildinfo for each package.

IIUC Trivy returns error, because we overwrite `rhel-8-for-x86_64-baseos-rpms` to `rhel-8-for-x86_64-baseos-rpms__8`.
So i can conclude that the layer contains more than one file.

**Comment by AdmiralGT** [comment]
I'm also seeing this error with the following content in content_manifests

```
[root@a481dbded621 /]# ls -l /root/buildinfo/content_manifests/
total 4
-rw-rw-r-- 1 root root 368 Oct 23  2023 ubi8-container-8.8-1067.1698056881.json
[root@a481dbded621 /]# cat /root/buildinfo/content_manifests/ubi8-container-8.8-1067.1698056881.json
{
    "metadata": {
        "icm_version": 1,
        "icm_spec": "https://raw.githubusercontent.com/containerbuildsystem/atomic-reactor/master/atomic_reactor/schemas/content_manifest.json",
        "image_layer_index": 0
    },
    "content_sets": [
        "rhel-8-for-x86_64-baseos-rpms",
        "rhel-8-for-x86_64-appstream-rpms"
    ],
    "image_contents": []
}
```

Based on the above comments, it looks like these are correct (and I only have a single file in content_manifests

**Comment by DmitriyLewen** [comment]
> I'm also seeing this error with the following content in content_manifests

Hmm... this is very strange...
Can you share this image?

**Comment by DmitriyLewen** [comment]
Trivy doesn't have `v0.55.5` version 😄

**Comment by AdmiralGT** [comment]
> Trivy doesn't have `v0.55.5` version 😄

Haha, I've not fully woken up yet, we've reverted to 0.55.0 (which does work) rather than 0.55.1 (which doesn't)

**Comment by DmitriyLewen** [comment]
> [root@a481dbded621 /]# ls -l /root/buildinfo/content_manifests/
total 4
-rw-rw-r-- 1 root root 368 Oct 23  2023 ubi8-container-8.8-1067.1698056881.json
[root@a481dbded621 /]# cat /root/buildinfo/content_manifests/ubi8-container-8.8-1067.1698056881.json
{
    "metadata": {
        "icm_version": 1,
        "icm_spec": "https://raw.githubusercontent.com/containerbuildsystem/atomic-reactor/master/atomic_reactor/schemas/content_manifest.json",
        "image_layer_index": 0
    },
    "content_sets": [
        "rhel-8-for-x86_64-baseos-rpms",
        "rhel-8-for-x86_64-appstream-rpms"
    ],
    "image_contents": []
}


Is this possible that manifest files for other layers have been deleted?

**Comment by AdmiralGT** [comment]
I don't believe so. Our build infrastructure templates our docker files but I couldn't find anything in the infrastructure to suggest it was deleting manifest files from other layers. I'll see if I can get out the templated docker file but that might not happen until next week I'm afraid.

**Comment by DmitriyLewen** [comment]
ok, i'll wait for the info.
i just can't think of any other ideas why you get an error with a valid context_sets

**Comment by andersjdba** [comment]
We started to see failures which directed to this issue after upgrading from trivy 0.55.1 to 0.56.1. We couldn't understand why we were seeing this and were at a bit of a loss. 

Rightly or wrongly, we've always scanned our images in our CI in parallel. Out of curiosity more than anything, I reverted the parallel scan to run in serial and this error went away. I haven't had chance to look in to the "why" as yet but thought id share this incase it helps in anyway without muddying the waters.

**Comment by bjd** [comment]
Seeing the same issue on standard amd64 UBI9 9.5 image (tested with trivy version: 0.57.0)

```
$ /home/dev/tools/trivy/trivy image registry.access.redhat.com/ubi9/ubi-minimal:9.5
2024-11-13T11:28:52Z    INFO    [vuln] Vulnerability scanning is enabled
2024-11-13T11:28:52Z    INFO    [secret] Secret scanning is enabled
2024-11-13T11:28:52Z    INFO    [secret] If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2024-11-13T11:28:52Z    INFO    [secret] Please see also https://aquasecurity.github.io/trivy/v0.57/docs/scanner/secret#recommendation for faster secret detection
2024-11-13T11:28:55Z    INFO    Detected OS     family="redhat" version="9.5"
2024-11-13T11:28:55Z    INFO    [redhat] Detecting RHEL/CentOS vulnerabilities...       os_version="9" pkg_num=105
2024-11-13T11:28:55Z    FATAL   Fatal error     image scan error: scan error: scan failed: scan failed: failed to detect vulnerabilities: unable to scan OS packages: failed vulnerability detection of OS packages: failed detection: redhat vulnerability detection error: failed to get Red Hat advisories: unable to find CPE indices. See https://github.com/aquasecurity/trivy-db/issues/435 for details
```
It has the following in content_manifests:

```
[root@b1c38098ed17 /]# ls -l /root/buildinfo/content_manifests
total 592
-rw-r--r--. 1 root root 479275 Nov  1 19:30 sbom-cyclonedx.json
-rw-r--r--. 1 root root 120511 Nov  1 19:30 sbom-purl.json
```

For comparison, the 9.4 version which works does not have the above manifests but a different one:
```
[root@85f0c1ce845b /]# ls -l /root/buildinfo/content_manifests/
total 4
-rw-rw-r--. 1 root root 368 Sep 18 21:24 ubi9-minimal-container-9.4-1227.1726694542.json
```

**Comment by DmitriyLewen** [comment]
Hello @bjd 
We already found this case - https://github.com/aquasecurity/trivy/issues/7911
eems to be a bug that `/root/buildinfo/content_manifests` doesn't contain a file with contentSet.

But in any case we should not return an error (in this case we should use default contentSets).
I created https://github.com/aquasecurity/trivy/pull/7912 to fix this issue.

**Comment by seebi** [comment]
I hope that v0.57.1 would solve this issue but unfortunately not:

```
∴ trivy --version; trivy image --scanners vuln --severity HIGH,CRITICAL  registry.access.redhat.com/ubi9/ubi-micro
Version: 0.57.1
Vulnerability DB:
  Version: 2
  UpdatedAt: 2024-10-23 06:16:55.145362881 +0000 UTC
  NextUpdate: 2024-10-24 06:16:55.14536257 +0000 UTC
  DownloadedAt: 2024-11-19 18:28:10.941552 +0000 UTC
Java DB:
  Version: 1
  UpdatedAt: 2024-11-15 03:03:12.781740813 +0000 UTC
  NextUpdate: 2024-11-18 03:03:12.781740492 +0000 UTC
  DownloadedAt: 2024-11-15 17:51:43.387032 +0000 UTC
2024-11-19T19:31:09+01:00	INFO	[vuln] Vulnerability scanning is enabled
2024-11-19T19:31:09+01:00	INFO	Detected OS	family="redhat" version="9.5"
2024-11-19T19:31:09+01:00	INFO	[redhat] Detecting RHEL/CentOS vulnerabilities...	os_version="9" pkg_num=20
2024-11-19T19:31:09+01:00	FATAL	Fatal error	image scan error: scan error: scan failed: scan failed: failed to detect vulnerabilities: unable to scan OS packages: failed vulnerability detection of OS packages: failed detection: redhat vulnerability detection error: failed to get Red Hat advisories: unable to find CPE indices. See https://github.com/aquasecurity/trivy-db/issues/435 for details
```

**Comment by gysel** [comment]
> I hope that v0.57.1 would solve this issue but unfortunately not:

I was able to run a UBI scan with `0.57.1` after I did a `trivy clean --all`.

**Comment by seebi** [comment]
@gysel I can confirm that this solves the problem. thx 👍🏻

**Comment by DmitriyLewen** [comment]
hello @atgreen 
We are working on fix for this error.

But can you share content sets for your image (see `json` files from `/root/buildinfo/content_manifests/`)?

**Comment by knqyf263** [comment]
@atgreen Please reference https://github.com/aquasecurity/trivy-db/issues/435#issuecomment-2368306012. The image you scanned also has invalid content sets.

**Comment by xrow** [comment]
I'm still experiencing this error with 0.58.1: https://github.com/aquasecurity/trivy-db/issues/435#issuecomment-2365157835
https://gitlab.com/xrow-public/ci-tools/-/jobs/8776737600#L31

**Comment by DmitriyLewen** [comment]
Hello @xrow 
Can you share scanned image?

Or send files from `/root/buildinfo/content_manifests/` (perhaps this is https://github.com/aquasecurity/trivy-db/issues/435#issuecomment-2367776616 case)

**Comment by xrow** [comment]
@DmitriyLewen 

The image was registry.gitlab.com/xrow-public/ci-tools/podman:0992d927fee75c507ef742d9d3f38cc3b447c060. I had some bad copy and paste stuff in the comment.

**Comment by DmitriyLewen** [comment]
@xrow 

I don't see error for this image:
```
➜  trivy -q image registry.gitlab.com/xrow-public/ci-tools/podman:0992d927fee75c507ef742d9d3f38cc3b447c060

registry.gitlab.com/xrow-public/ci-tools/podman:0992d927fee75c507ef742d9d3f38cc3b447c060 (redhat 9.5)

Total: 219 (UNKNOWN: 0, LOW: 161, MEDIUM: 56, HIGH: 2, CRITICAL: 0)
```

If you have image with stable error - you can send it to me for research.

PS. don't forget to clear cache after updating Trivy to `v0.58.1` if you scan images locally (https://github.com/aquasecurity/trivy-db/issues/435#issuecomment-2486603118).

**Comment by lm-sig** [comment]
After seeing this fixed I am encountering it again on a new UBI 9 image. Version 0.57.1. Running "--clean" before the scan does not help.

image: registry.redhat.io/ubi9/python-312@sha256:9b84a91c94aa7e7ebfcd416db7857610bc7872ba6170cfa7b0753590d4b71dd0

```sh
(app-root) ls -la /root/buildinfo/content_manifests/
total 4
drwxr-xr-x. 1 root root  31 Jan  8 12:15 .
drwxr-xr-x. 1 root root  31 Jan  8 05:06 ..
-rw-r--r--. 1 root root 387 Jan  8 12:15 content-sets.json
```

/root/buildinfo/content_manifests/content-sets.json
```json
{
  "metadata": {
    "icm_version": 1,
    "icm_spec": "https://raw.githubusercontent.com/containerbuildsystem/atomic-reactor/master/atomic_reactor/schemas/content_manifest.json",
    "image_layer_index": 0
  },
  "from_dnf_hint": true,
  "content_sets": [
    "rhel-9-appstream-rpms",
    "rhel-9-appstream-source-rpms",
    "rhel-9-baseos-rpms",
    "rhel-9-baseos-source-rpms"
  ]
}
```

The previous UBI 9 image that worked looked like this:

image: registry.redhat.io/ubi9/python-312@sha256:1d8846b7c6558a50b434f1ea76131f200dcdd92cfaf16b81996003b14657b491

```
(app-root) ls -l /root/buildinfo/content_manifests/
total 1160
-rw-r--r--. 1 root root 974658 Nov 28 14:34 sbom-cyclonedx.json
-rw-r--r--. 1 root root 210101 Nov 28 14:34 sbom-purl.json
```

**Comment by DmitriyLewen** [comment]
both images works correcty :
```
➜  trivy571 -v
Version: 0.57.1

➜  trivy571 clean --all
2025-01-10T10:46:01+06:00	INFO	Removing scan cache...
2025-01-10T10:46:01+06:00	INFO	Removing vulnerability database...
2025-01-10T10:46:01+06:00	INFO	Removing Java database...
2025-01-10T10:46:01+06:00	INFO	Removing check bundle...
2025-01-10T10:46:01+06:00	INFO	Removing VEX repositories...
➜  trivy571 -q image --severity CRITICAL registry.redhat.io/ubi9/python-312@sha256:9b84a91c94aa7e7ebfcd416db7857610bc7872ba6170cfa7b0753590d4b71dd0 

registry.redhat.io/ubi9/python-312@sha256:9b84a91c94aa7e7ebfcd416db7857610bc7872ba6170cfa7b0753590d4b71dd0 (redhat 9.5)

Total: 0 (CRITICAL: 0)

➜  trivy571 -q image --severity CRITICAL registry.redhat.io/ubi9/python-312@sha256:1d8846b7c6558a50b434f1ea76131f200dcdd92cfaf16b81996003b14657b491 

registry.redhat.io/ubi9/python-312@sha256:1d8846b7c6558a50b434f1ea76131f200dcdd92cfaf16b81996003b14657b491 (redhat 9.5)

Total: 0 (CRITICAL: 0)

````

Can you share logs with `--debug` flag for `registry.redhat.io/ubi9/python-312@sha256:9b84a91c94aa7e7ebfcd416db7857610bc7872ba6170cfa7b0753590d4b71dd0 image?

**Comment by lm-sig** [comment]
I retried the scan today and... it worked. :(

I will capture debug output the next time I see it, which is hopefully never. Thank you.

**Comment by wagde-orca** [comment]
i am still having problem with some images that should be scanned
I have an image with
"Created": "2022-01-25T11:30:04.726931532Z",
"Architecture": "amd64",

and when I try to scan it I get the error (I am using latest trivy 0.58.2 and ran trivy clean --all before)
```
2025-01-23T12:23:29+02:00	DEBUG	[image] Detected base layers	diff_ids=[]
2025-01-23T12:23:29+02:00	INFO	Detected OS	family="redhat" version="8.4"
2025-01-23T12:23:29+02:00	INFO	[redhat] Detecting RHEL/CentOS vulnerabilities...	os_version="8" pkg_num=232
2025-01-23T12:23:29+02:00	FATAL	Fatal error
  - image scan error:
    github.com/aquasecurity/trivy/pkg/commands/artifact.Run
        github.com/aquasecurity/trivy/pkg/commands/artifact/run.go:387
  - scan error:
    github.com/aquasecurity/trivy/pkg/commands/artifact.(*runner).scanArtifact
        github.com/aquasecurity/trivy/pkg/commands/artifact/run.go:261
  - scan failed:
    github.com/aquasecurity/trivy/pkg/commands/artifact.(*runner).scan
        github.com/aquasecurity/trivy/pkg/commands/artifact/run.go:622
  - scan failed:
    github.com/aquasecurity/trivy/pkg/scanner.Scanner.ScanArtifact
        github.com/aquasecurity/trivy/pkg/scanner/scan.go:169
  - failed to detect vulnerabilities:
    github.com/aquasecurity/trivy/pkg/scanner/local.Scanner.ScanTarget
        github.com/aquasecurity/trivy/pkg/scanner/local/scan.go:117
  - unable to scan OS packages:
    github.com/aquasecurity/trivy/pkg/scanner/local.Scanner.scanVulnerabilities
        github.com/aquasecurity/trivy/pkg/scanner/local/scan.go:168
  - failed vulnerability detection of OS packages:
    github.com/aquasecurity/trivy/pkg/scanner/ospkg.(*scanner).Scan
        github.com/aquasecurity/trivy/pkg/scanner/ospkg/scan.go:57
  - failed detection:
    github.com/aquasecurity/trivy/pkg/detector/ospkg.Detect
        github.com/aquasecurity/trivy/pkg/detector/ospkg/detect.go:83
  - redhat vulnerability detection error:
    github.com/aquasecurity/trivy/pkg/detector/ospkg/redhat.(*Scanner).Detect
        github.com/aquasecurity/trivy/pkg/detector/ospkg/redhat/redhat.go:92
  - failed to get Red Hat advisories:
    github.com/aquasecurity/trivy/pkg/detector/ospkg/redhat.(*Scanner).detect
        github.com/aquasecurity/trivy/pkg/detector/ospkg/redhat/redhat.go:114
  - unable to find CPE indices. See https://github.com/aquasecurity/trivy-db/issues/435 for details:
    github.com/aquasecurity/trivy-db/pkg/vulnsrc/redhat-oval.VulnSrc.Get
        github.com/aquasecurity/trivy-db@v0.0.0-20241209111357-8c398f13db0e/pkg/vulnsrc/redhat-oval/redhat-oval.go:252
```

**Comment by DmitriyLewen** [comment]
I think your image contains invalid `content_sets` (see https://github.com/aquasecurity/trivy-db/issues/435#issuecomment-2490139813).

check your `/root/buildinfo/content_manifests/*.json` files

**Comment by wagde-orca** [comment]
`cat /root/buildinfo/content_manifests/openjdk-8-ubi8-container-1.3-15.json
{
    "metadata": {
        "icm_version": 1,
        "icm_spec": "https://raw.githubusercontent.com/containerbuildsystem/atomic-reactor/master/atomic_reactor/schemas/content_manifest.json",
        "image_layer_index": 2
    },
    "content_sets": [
        "ubi-8-for-x86_64-baseos-rpms__8",
        "ubi-8-for-x86_64-appstream-rpms__8"
    ],
    "image_contents": []
}`


`cat /root/buildinfo/content_manifests/ubi8-minimal-container-8.4-205.1626828526.json
{
    "metadata": {
        "icm_version": 1,
        "icm_spec": "https://raw.githubusercontent.com/containerbuildsystem/atomic-reactor/master/atomic_reactor/schemas/content_manifest.json",
        "image_layer_index": 1
    },
    "content_sets": [
        "rhel-8-for-x86_64-baseos-rpms",
        "rhel-8-for-x86_64-appstream-rpms"
    ],
    "image_contents": []
}`

**Comment by DmitriyLewen** [comment]
@wagde-orca This is case as in https://github.com/aquasecurity/trivy-db/issues/435#issuecomment-2367776616
`ubi-8-for-x86_64-baseos-rpms__8` is incorrect.

You can see all repositories in https://security.access.redhat.com/data/metrics/repository-to-cpe.json

**Comment by wagde-orca** [comment]
@DmitriyLewen any workaround for this? or plans to fix it?

**Comment by DmitriyLewen** [comment]
Hello @wagde-orca 
We currently tnink this is bug in RedHat images and they should fix it (because we have no information how we can compare incorrect (e.g. `ubi-8-for-x86_64-baseos-rpms__8`) content_sets:
- we can't remove the incorrect suffix because we are not sure that `ubi-8-for-x86_64-baseos-rpms__8` is equal to `ubi-8-for-x86_64-baseos-rpms`.
- we can't skip (or use default content_sets) packages with incorrect content_sets (even with a warning in the log) because users will miss it and may use vulnerable packages without knowing it.


____


hello @sayan-biswas 
Sorry for the ping, but we need your help.
Can you clarify: `ubi-8-for-x86_64-baseos-rpms__8` is a valid content_set? (https://github.com/aquasecurity/trivy-db/issues/435#issuecomment-2368306012).
Or is this a bug and we can trim the `__8` suffix (and use `ubi-8-for-x86_64-baseos-rpms`)?

**Comment by ChristianLoewel** [comment]
Hello @DmitriyLewen,

I contacted Red Hat Support to ask about these __8 suffixes as I'm also affected by this. Here's their response:

> I would like to tell you that I had a detailed discussion with the engineering and according to them, content set without "suffix" or version such as `rhocp-4.14-for-rhel-9-x86_64-rpms` are the valid ones and are valid if your image is built from the mainline (standard) RHEL repos,( not using EUS ). The suffixes( i.e __9_DOT_2 ) are meant only for specific RHEL EUS versions, not for regular UBI8 images. So, if your image is built using EUS (xUS) repos — like RHEL 9.2 EUS, then the content set should be specific: `rhel-9-...__9_DOT_2` and it should match what's listed in the official `repository-to-cpe.json` and this would work for the scanners as in your case.
>
>But, if you see only `__8`, that’s likely too generic or incorrect for EUS and may break tooling (like security scanners). If your image is built from the mainline (standard) RHEL repos, not using EUS then it's okay for the content set to have no suffix, or a generic one like `__8`. These generic suffixes are harmless for non-EUS builds and can usually be ignored.
>
>Basically, these suffixes are meant only for specific RHEL EUS versions (like __9_DOT_2), not for regular UBI9 images.
>
>So, for now you can either trim the suffix for the scanner to work( which is not recommended by RedHat ) or you could wait for a month before this issue is resolved as Red Hat will be migrated to Konflux( new build system ) in which the problem with the __8 suffix will be automatically fixed.

Apparently, these generic suffixes are a bug on Red Hat's end, and it's okay to cut them.

**Comment by knqyf263** [comment]
@ChristianLoewel Thanks for the information! It's good to know that it's a bug on Red Hat's side, as we expected. Cutting the suffix wouldn't seem to cause any issues, but I'm a little concerned about the fact that it's not recommended by Red Hat...

> which is not recommended by RedHat

**Comment by ChristianLoewel** [comment]
I guess it would be the only way to fix scanning for old affected images that were created before Red Hat's fix. Should be fine as long as it's ensured that only incomplete suffixes are truncated. I'll check back with them and ask for any specific reasons why it's not recommended.

**Comment by ChristianLoewel** [comment]
Got another response:

> Regarding truncating generic suffixes is not recommended by Red Hat, its specially for the *US streams but since this issue is the one which can only be resolved by trimming the suffix or waiting for openshift to migrate to Konflux , so as per my further discussions with engineering, you can move forward to trim the suffix for your scanners to work properly.

As I read it, Red Hat is okay with this as long as only the generic suffixes are cut, not the correct EUS suffixes.

**Comment by knqyf263** [comment]
@ChristianLoewel Thanks for sharing that. We added trimming of the malformed suffixes. It should mitigate this problem.
https://github.com/aquasecurity/trivy/pull/8818

This will be included in [v0.63.0](https://github.com/aquasecurity/trivy/milestone/49).

**Comment by Romain-Geissler-1A** [comment]
Hi,

For people landing here, there are other possibilities for having this message:
 - Your image no longer has /root/buildinfo/content_manifests. Recently Red Hat has moved these json files inside /usr/share/buildinfo (as announced by Red Hat here: https://github.com/aquasecurity/trivy/discussions/8209). Then you should make sure you use an up to date Trivy to have it read /usr/share/buildinfo as well (Trivy >= 0.59.0).
 - Your image is actually recognized as a Red Hat image, but still is not fully recognized. Typically because you use a new major version of RHEL, like RHEL 10 released recently. Then the error message is misleading, the real problem is that Trivy doesn't know yet about this major version and support shall be added, like in https://github.com/aquasecurity/trivy/pull/8910

**Comment by candrews** [comment]
Using Trivy 0.67.2, using `trivy image` works:
```
$ trivy image redhat/ubi10
2025-10-16T13:27:27-04:00	INFO	[vuln] Vulnerability scanning is enabled
2025-10-16T13:27:27-04:00	INFO	[secret] Secret scanning is enabled
2025-10-16T13:27:27-04:00	INFO	[secret] If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2025-10-16T13:27:27-04:00	INFO	[secret] Please see https://trivy.dev/v0.67/docs/scanner/secret#recommendation for faster secret detection
2025-10-16T13:27:30-04:00	INFO	[python] Licenses acquired from one or more METADATA files may be subject to additional terms. Use `--debug` flag to see all affected packages.
2025-10-16T13:27:30-04:00	INFO	Detected OS	family="redhat" version="10.0"
2025-10-16T13:27:30-04:00	INFO	[redhat] Detecting RHEL/CentOS vulnerabilities...	os_version="10" pkg_num=172
2025-10-16T13:27:30-04:00	INFO	Number of language-specific files	num=0

Report Summary

┌────────────────────────────┬────────┬─────────────────┬─────────┐
│           Target           │  Type  │ Vulnerabilities │ Secrets │
├────────────────────────────┼────────┼─────────────────┼─────────┤
│ redhat/ubi10 (redhat 10.0) │ redhat │        0        │    -    │
└────────────────────────────┴────────┴─────────────────┴─────────┘
Legend:
- '-': Not scanned
- '0': Clean (no security findings detected)
```

However, generating an SBOM then scanning it does not:
```
$ trivy image --format cyclonedx --output test.cdx.json redhat/ubi10 && trivy sbom test.cdx.json 
2025-10-16T13:28:40-04:00	INFO	"--format cyclonedx" disables security scanning. Specify "--scanners vuln" explicitly if you want to include vulnerabilities in the "cyclonedx" report.
2025-10-16T13:28:42-04:00	INFO	Detected OS	family="redhat" version="10.0"
2025-10-16T13:28:42-04:00	INFO	Number of language-specific files	num=0
2025-10-16T13:28:42-04:00	INFO	[vuln] Vulnerability scanning is enabled
2025-10-16T13:28:42-04:00	INFO	Detected SBOM format	format="cyclonedx-json"
2025-10-16T13:28:42-04:00	INFO	Detected OS	family="redhat" version="10.0"
2025-10-16T13:28:42-04:00	INFO	[redhat] Detecting RHEL/CentOS vulnerabilities...	os_version="10" pkg_num=172
2025-10-16T13:28:42-04:00	FATAL	Fatal error	run error: sbom scan error: scan error: scan failed: scan failed: failed to detect vulnerabilities: unable to scan OS packages: failed vulnerability detection of OS packages: failed detection: redhat vulnerability detection error: failed to get Red Hat advisories: unable to find CPE indices. See https://github.com/aquasecurity/trivy-db/issues/435 for details
[1]
```

I reported this issue at https://github.com/aquasecurity/trivy/discussions/9679

**Comment by pfuntner** [comment]
> Hello [@candrews](https://github.com/candrews)
> 
> This happens because Trivy currently doesn’t support vulnerability detection for Red Hat 10. However, it might be worth making the error message clearer for users.

Is this still a problem?  Is there a ticket specific to Red Hat 10?

**Comment by DmitriyLewen** [comment]
Hello @pfuntner 
https://github.com/aquasecurity/trivy/issues/7452
