### ISSUE TITLE
Trivy-db cannot be pulled (toomanyrequests)

### ISSUE THREAD

**Issue by idrissneumann** [aquasecurity/trivy-db#465]
Hi.

It seems that there's too many requests on the registry:

```shell
$ docker pull ghcr.io/aquasecurity/trivy-db:2
Error response from daemon: toomanyrequests: retry-after: 755.31µs, allowed: 44000/minute
```

I reproduced it on my laptop (and it failed very quickly).

<img width="869" alt="Screenshot 2024-11-04 at 15 28 17" src="https://github.com/user-attachments/assets/f8756a5a-0a69-4bdf-a7a0-d8107b8d706f">

It seems like a global quota issue.

Thanks

**Comment by jrtitus** [comment]
It seems they address this in their troubleshooting guide: https://aquasecurity.github.io/trivy/v0.57/docs/references/troubleshooting/#github-rate-limiting

However, from my own testing, this also does not always work.

**Comment by idrissneumann** [comment]
> However, from my own testing, this also does not always work.

Yeah especially if you're not a customer of ghcr ^^

It might be better to publish on other public registries (at least docker.io) and let users decide and purchase subscriptions or reuse the ones they already purchased :)

**Comment by knqyf263** [comment]
Please reference https://github.com/aquasecurity/trivy/discussions/7699
