### ISSUE TITLE
Scheduled "Trivy DB" actions in this repository are failing - no new databases are being published!

### ISSUE THREAD

**Issue by malmor** [aquasecurity/trivy-db#470]
The scheduled GitHub actions for publishing the trivy-db are currently not working: https://github.com/aquasecurity/trivy-db/actions

This leads to old / outdated databases in the official repositories: https://github.com/aquasecurity/trivy-db/pkgs/container/trivy-db/305009031?tag=2

```
{
  "labels": {
    "org.opencontainers.image.created": "2024-11-13T12:20:50Z"
  }
}
```

Clients also show this:

```bash
$ trivy --version

Version: 0.57.0
Vulnerability DB:
  Version: 2
  UpdatedAt: 2024-11-13 12:18:59.293858632 +0000 UTC
  NextUpdate: 2024-11-14 12:18:59.293858261 +0000 UTC
  DownloadedAt: 2024-12-14 14:44:30.527509 +0000 UTC
Java DB:
  Version: 1
  UpdatedAt: 2024-09-17 01:05:13.063235569 +0000 UTC
  NextUpdate: 2024-09-20 01:05:13.063235449 +0000 UTC
  DownloadedAt: 2024-09-17 19:40:20.201706 +0000 UTC
```

This triggers many database downloads because the local trivy-db copy will always be outdated (excluding an one hour grace period after the download).

**Comment by knqyf263** [comment]
You can track https://github.com/aquasecurity/trivy-db/issues/468

**Comment by malmor** [comment]
Thanks @knqyf263,
I did not realize that the bug is the cause of the failing pipelines. I will follow it there 👍

**Comment by knqyf263** [comment]
Yes, Microsoft changed the data format.
