### ISSUE TITLE
starboard find vulns deployment/some_deployment throws `certificate signed by unknown authority`

### ISSUE THREAD

**Issue by larssb** [aquasecurity/trivy-db#51]
__ISSUE__

```
starboard find vulns deployment/some_deployment --namespace default -v 3
I0708 14:43:53.094626    3804 scanner.go:55] Getting Pod template for workload: {Deployment core-scanandpay-failover-v2 default}
I0708 14:43:53.117105    3804 scanner.go:70] Scanning with options: {ScanJobTimeout:0s DeleteScanJob:true}
I0708 14:43:53.118220    3804 runner.go:79] Running task and waiting forever
I0708 14:43:53.118288    3804 runnable_job.go:47] Creating runnable job: starboard/2e7c4482-df93-4057-a5b1-dbc1a18ce353
I0708 14:43:53.137715    3804 reflector.go:207] Starting reflector *v1.Job (30m0s) from pkg/mod/k8s.io/client-go@v0.19.0-alpha.3/tools/cache/reflector.go:156
I0708 14:43:53.138252    3804 reflector.go:243] Listing and watching *v1.Job from pkg/mod/k8s.io/client-go@v0.19.0-alpha.3/tools/cache/reflector.go:156
I0708 14:43:55.586801    3804 runnable_job.go:73] Stopping runnable job on task failure with status: Failed
I0708 14:43:55.587514    3804 runner.go:83] Stopping runner on task completion with error: job failed: BackoffLimitExceeded: Job has reached the specified backoff limit
E0708 14:43:55.723818    3804 manager.go:177] Container 2e7c4482-df93-4057-a5b1-dbc1a18ce353 terminated with Error: 2020-07-08T12:43:54.563Z                                                                       INFO     Need to update DB
2020-07-08T12:43:54.564Z        INFO    Downloading DB...
2020-07-08T12:43:54.730Z        FATAL   failed to download vulnerability DB: failed to download vulnerability DB: failed to list releases: Get https://api.github.com/repos/aquasecurity/trivy-db/releases: x509: certificate signed by unknown authority
error: running scan job: job failed: BackoffLimitExceeded: Job has reached the specified backoff limit
```

__TECHNICAL DETAILS__

- K8S version: 1.14.6
- starboard version: 0.2.5
- K8S runs on a VMWare platform on-prem
  - Behind a corporate FW and proxy.
- kubectl version: 1.17.3

__EXPECTATIONS__

To be able to execute `starboard find vulns deployment/some_deployment` without this issue

__DEBUGGING - TRIED__

* Tried using: `--insecure-skip-tls-verify` the issue remained
* Tried removing the `certificate-authority-data` sections from the **kubeconfig** file. The issue remained
  * Tried with and without the `--insecure-skip-tls-verify` parameter. Same issue

__OTHER__

I'm posting this issue in this repo as the challenge seems to be related to specifically `trivy-db`. As that is being called via `starboard`.

Looking forward to any tips and pointers. Let me know if more info is needed.

Thank you very much.

**Comment by knqyf263** [comment]
Does it still reproduce? If so, could you open the issue in Starboard? `trivy-db` itself works properly in my environment.

**Comment by larssb** [comment]
Hi @knqyf263,

Yes it does reproduce. With exactly the same error. Had anything changed since you ask if it still reproduces? I'll happily create this issue in the `starboard` repo.

**Comment by knqyf263** [comment]
A network problem sometimes displays certification error.

**Comment by larssb** [comment]
Ah okay. I’ll wait and see what the response to the issue is in the “starboard” repo.

--
Mvh. / Kind regards
Lars Bengtsson

- Health is wealth, movement is medicine -

**Comment by larssb** [comment]
It's not an issue with *trivy* ... Therefore closing this 1. For those interested. Please follow the issue in the *starboard* repo.
