### ISSUE TITLE
Help command or flags?

### ISSUE THREAD

**Issue by neha-viswanathan** [aquasecurity/trivy-db#76]
Currently, we have both flags and command for help.

```
trivy-db  
NAME:
   trivy-db - Trivy DB builder

USAGE:
   trivy-db [global options] command [command options] image_name

VERSION:
   0.0.1

COMMANDS:
   build    build a database file
   upload   upload database files to GitHub Release
   help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --help, -h     show help
   --version, -v  print the version
```

We may want to have one, not both.

**Comment by knqyf263** [comment]
The same as https://github.com/aquasecurity/trivy/issues/670#issuecomment-704141523

**Comment by shreegowtham27** [comment]
Please assign this task :)

**Comment by knqyf263** [comment]
@shreegowtham27 Thanks for your offer, but we don't have a plan to drop the command for help at the moment. Let me know if there is any reason to drop one of them.

**Comment by shreegowtham27** [comment]
@knqyf263  To my understanding I think that let's go with a flag version of help or command version of help. Please correct me if I misunderstood the context.
