### ISSUE TITLE
Binary committed to the repo?

### ISSUE THREAD

**Issue by neha-viswanathan** [aquasecurity/trivy-db#79]
Hi @simar7 any reason why the trivy-db binary is part of the repo - https://github.com/aquasecurity/trivy-db/blob/master/cmd/trivy-db/trivy-db? I have a PR to remove it, please feel free to close it, if it's irrelevant. Thanks!

**Comment by simar7** [comment]
> Hi @simar7 any reason why the trivy-db binary is part of the repo - https://github.com/aquasecurity/trivy-db/blob/master/cmd/trivy-db/trivy-db? I have a PR to remove it, please feel free to close it, if it's irrelevant. Thanks!

thanks for the PR! - good catch.
